name: dc-gan-gen-cifar10-to-cifar10
dataset: 
  name: cifar10
  image_size: 32
  num_workers: 1

model: 
  name: simsiam
  backbone: resnet18_cifar_variant1
  proj_layers: 2

eval: # for training the generator
#  optimizer:
#    name: sgd
#    weight_decay: 0
#    momentum: 0.9
#  warmup_lr: 0
#  warmup_epochs: 0
  base_lr: 0.01
  final_lr: 0
  batch_size: 256
  num_epochs: 100
logger:
  tensorboard: False
  matplotlib: False


train: null
seed: null
